/* =====================================================
   APPLICATION ORCHESTRATOR
   Connects all modules, controls navigation, global search,
   lazy rendering, pagination, sorting, login state, and page
   titles for the offline NDA command system.
===================================================== */
const App={currentUser:null,pageSize:25,nav:[['Dashboard','📊',()=>Dashboard.render()],['Vehicles','🚙',()=>Vehicles.render()],['Maintenance Jobs','🛠️',()=>Maintenance.render()],['Servicing Schedule','📅',()=>Servicing.render()],['Inventory','📦',()=>Inventory.render()],['Notifications','🔔',()=>Notifications.render()],['Reports','🖨️',()=>Reports.render()],['Audit Logs','🧾',()=>Audit.render()],['Users','👥',()=>Users.render()],['Settings','⚙️',()=>App.settings()]],
/** Boot storage, seed data, and bind login/navigation. */
async init(){await Storage.init();await Storage.seed();this.currentUser=JSON.parse(localStorage.getItem('ndaCurrentUser')||'null');this.bindLogin();if(this.currentUser)this.showApp();},
/** Attach login handlers. */
bindLogin(){document.getElementById('login-form').onsubmit=async e=>{e.preventDefault();const d=formData(e.target);const u=await Users.login(d.username,d.password);if(!u){document.getElementById('login-error').textContent='Invalid NDA command credentials.';return}this.currentUser=u;localStorage.setItem('ndaCurrentUser',JSON.stringify(u));await Audit.log('Login','Users',u.username);this.showApp();};document.getElementById('logout-btn').onclick=async()=>{await Audit.log('Logout','Users',this.currentUser.username);localStorage.removeItem('ndaCurrentUser');location.reload();};document.getElementById('toggle-sidebar').onclick=()=>document.getElementById('sidebar').classList.toggle('collapsed');document.getElementById('global-search').oninput=e=>this.globalSearch(e.target.value);},
/** Show authenticated application shell. */
showApp(){document.getElementById('login-screen').classList.add('hidden');document.getElementById('app').classList.remove('hidden');document.getElementById('current-user').textContent=`${this.currentUser.name} • ${this.currentUser.role}`;this.renderNav();this.route('Dashboard',Dashboard.render);},
/** Render sidebar navigation. */
renderNav(){document.getElementById('nav').innerHTML=this.nav.map(n=>`<button data-page="${n[0]}"><span>${n[1]}</span><span class="nav-label">${n[0]}</span></button>`).join('');[...document.querySelectorAll('#nav button')].forEach((b,i)=>b.onclick=()=>this.route(this.nav[i][0],this.nav[i][2]));},
/** Navigate to a module. */
route(title,fn){document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===title));document.getElementById('page-title').textContent=title;fn();},
/** Generate reusable entity form HTML. */
formHtml(title,fields,edit={},selects={}){return `<form class="card inline-form" id="entity-form"><h3>${edit.id?'Edit':'Add'} ${title}</h3><input type="hidden" name="id" value="${esc(edit.id||'')}"><div class="form-grid">${fields.map(f=>`<label class="${f==='notes'?'wide':''}">${f.replace(/([A-Z])/g,' $1')} ${selects[f]?`<select name="${f}">${selects[f].map(o=>`<option ${edit[f]===o?'selected':''}>${o}</option>`).join('')}</select>`:f==='notes'?`<textarea name="${f}">${esc(edit[f]||'')}</textarea>`:`<input name="${f}" value="${esc(edit[f]||'')}" ${f.toLowerCase().includes('date')?'type="date"':f.toLowerCase().includes('cost')||f.toLowerCase().includes('mileage')||['quantity','minimum','unitCost'].includes(f)?'type="number"':''}>`}</label>`).join('')}</div><div class="form-actions"><button class="btn btn-primary">Save</button><button type="button" class="btn btn-ghost" onclick="document.getElementById('entity-form').reset()">Clear</button></div></form>`;},
/** Render paginated, sortable table into content or table slot. */
renderTable(title,rows,fields,onDelete,store,append=false,onEdit=null,extra=null){const slot=append&&document.getElementById('table-slot')?document.getElementById('table-slot'):document.getElementById('content');let page=1,sort=fields[0],dir=1,query='';const draw=async()=>{let data=rows.filter(r=>JSON.stringify(r).toLowerCase().includes(query));data.sort((a,b)=>String(a[sort]||'').localeCompare(String(b[sort]||''))*dir);const pages=Math.max(1,Math.ceil(data.length/this.pageSize));page=Math.min(page,pages);const slice=data.slice((page-1)*this.pageSize,page*this.pageSize);slot.innerHTML=`<div class="toolbar"><h3>${title}</h3><input placeholder="Search / filter ${title}" oninput="this.dispatchEvent(new CustomEvent('localfilter',{bubbles:true,detail:this.value.toLowerCase()}))"></div>${this.tableHtml(slice,fields,true,onDelete,onEdit,extra,store)}<div class="pagination"><button class="btn btn-small btn-ghost" id="prev">Prev</button><span>Page ${page} of ${pages} • ${data.length} records</span><button class="btn btn-small btn-ghost" id="next">Next</button></div>`;slot.querySelectorAll('th[data-f]').forEach(th=>th.onclick=()=>{sort=th.dataset.f;dir*=-1;draw();});slot.querySelector('#prev').onclick=()=>{page=Math.max(1,page-1);draw();};slot.querySelector('#next').onclick=()=>{page=Math.min(pages,page+1);draw();};slot.addEventListener('localfilter',e=>{query=e.detail;page=1;draw();},{once:true});};draw();},
/** Build table markup. */
tableHtml(rows,fields,actions=false,onDelete=null,onEdit=null,extra=null,store=''){return `<div class="table-wrap"><table><thead><tr>${fields.map(f=>`<th data-f="${f}">${f}</th>`).join('')}${actions?'<th>Actions</th>':''}</tr></thead><tbody>${rows.map(r=>`<tr>${fields.map(f=>`<td>${String(f).toLowerCase().includes('cost')?naira(r[f]):`<span class="pill ${esc(r[f])}">${esc(r[f])}</span>`}</td>`).join('')}${actions?`<td>${onEdit?`<button class="btn btn-small btn-ghost" onclick="(${onEdit})('${r.id}')">Edit</button>`:''} ${onDelete?`<button class="btn btn-small btn-danger" onclick="(${onDelete})('${r.id}')">Delete</button>`:''} ${store==='maintenance'?`<select onchange="Maintenance.setStatus('${r.id}',this.value)">${JobStatuses.map(s=>`<option ${s===r.status?'selected':''}>${s}</option>`).join('')}</select>`:''}${store==='inventory'?` <button class="btn btn-small btn-ghost" onclick="Inventory.use('${r.id}',1)">Use 1</button>`:''}</td>`:''}</tr>`).join('')}</tbody></table></div>`;},
/** Run global search across operational modules. */
async globalSearch(q){if(!q){Dashboard.render();return}q=q.toLowerCase();const stores=['vehicles','maintenance','servicing','inventory','notifications'];let results=[];for(const s of stores)(await Storage.all(s)).forEach(r=>{if(JSON.stringify(r).toLowerCase().includes(q))results.push({module:s,reference:r.vehicleId||r.jobNumber||r.partNumber||r.title||r.id,summary:JSON.stringify(r).slice(0,180)});});document.getElementById('page-title').textContent='Global Search';this.renderTable('Global Search Results',results,['module','reference','summary'],null,'search');},
/** Render offline settings and data export/import. */
settings(){document.getElementById('content').innerHTML=`<div class="card"><h3>Settings</h3><p>Offline mode active. Data is stored in IndexedDB/localStorage on this browser only.</p><button class="btn btn-primary" onclick="Notifications.generate().then(()=>alert('Alerts generated'))">Run Alert Scan</button></div>`;}
};
document.addEventListener('DOMContentLoaded',()=>App.init());
