/* =====================================================
   REPORTING MODULE
   Generates printable NDA reports using window.print() for
   vehicles, maintenance, servicing, inventory, costs,
   notifications, officer name, and signature sections.
===================================================== */
const Reports={types:{'Vehicle Report':['vehicles',Vehicles.fields],'Maintenance Report':['maintenance',Maintenance.fields],'Servicing Report':['servicing',[...Servicing.fields,'daysUntilService','mileageUntilService','daysOverdue','mileageOverdue']],'Inventory Report':['inventory',Inventory.fields],'Notification Report':['notifications',['date','priority','title','message','module','ref']]},
/** Render report selector and printable report output. */
async render(){document.getElementById('content').innerHTML=`<div class="toolbar"><h3>Printable Reports</h3><div><input id="officer" placeholder="Officer Name"><select id="report-type">${Object.keys(this.types).map(t=>`<option>${t}</option>`).join('')}<option>Cost Report</option></select><button class="btn btn-primary" onclick="Reports.build()">Generate</button><button class="btn btn-ghost" onclick="window.print()">Print</button></div></div><div id="report-output" class="card">Select a report to generate.</div>`;},
/** Build selected report table. */
async build(){const type=document.getElementById('report-type').value;const officer=document.getElementById('officer').value||App.currentUser.name;let html=`<div class="print-header"><h2>Nigerian Defence Academy</h2><h3>Fleet Maintenance & Logistics Command</h3></div><h2>${type}</h2><p>Date Generated: ${new Date().toLocaleString()}<br>Officer Name: ${esc(officer)}</p>`;if(type==='Cost Report'){const m=await Storage.all('maintenance'), inv=await Storage.all('inventory');const costs=[['Maintenance Cost',m.reduce((s,x)=>s+Number(x.actualCost||x.estimatedCost||0),0)],['Spare Part Cost',inv.reduce((s,x)=>s+Number(x.quantity)*Number(x.unitCost),0)],['Workshop Cost',m.reduce((s,x)=>s+Number(x.actualCost||0)*.25,0)],['Procurement Cost',inv.reduce((s,x)=>s+Number(x.unitCost),0)],['Logistics Cost',m.reduce((s,x)=>s+Number(x.estimatedCost||0),0)]];html+=`<ul class="metric-list">${costs.map(c=>`<li><span>${c[0]}</span><b>${naira(c[1])}</b></li>`).join('')}</ul>`;}else{let [store,fields]=this.types[type];let rows=await Storage.all(store);if(store==='servicing')rows=rows.map(Servicing.metrics);html+=App.tableHtml(rows,fields,false);}html+=`<div style="margin-top:60px">Signature: ____________________________</div>`;document.getElementById('report-output').innerHTML=html;}
};
